-- MySQL Script generated by MySQL Workbench
-- dom 23 dic 2018 17:52:33 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mglezsosa-filmaffinity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mglezsosa-filmaffinity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mglezsosa-filmaffinity` DEFAULT CHARACTER SET utf8 ;
USE `mglezsosa-filmaffinity` ;

-- -----------------------------------------------------
-- Table `mglezsosa-filmaffinity`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mglezsosa-filmaffinity`.`Director` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mglezsosa-filmaffinity`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mglezsosa-filmaffinity`.`Movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `genre` VARCHAR(255) NULL,
  `year` INT NULL,
  `Director_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Movie_Director_idx` (`Director_id` ASC),
  CONSTRAINT `fk_Movie_Director`
    FOREIGN KEY (`Director_id`)
    REFERENCES `mglezsosa-filmaffinity`.`Director` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mglezsosa-filmaffinity`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mglezsosa-filmaffinity`.`Actor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mglezsosa-filmaffinity`.`Movie_has_Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mglezsosa-filmaffinity`.`Movie_has_Actor` (
  `Movie_id` INT NOT NULL,
  `Actor_id` INT NOT NULL,
  PRIMARY KEY (`Movie_id`, `Actor_id`),
  INDEX `fk_Movie_has_Actor_Actor1_idx` (`Actor_id` ASC),
  INDEX `fk_Movie_has_Actor_Movie1_idx` (`Movie_id` ASC),
  CONSTRAINT `fk_Movie_has_Actor_Movie1`
    FOREIGN KEY (`Movie_id`)
    REFERENCES `mglezsosa-filmaffinity`.`Movie` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Actor_Actor1`
    FOREIGN KEY (`Actor_id`)
    REFERENCES `mglezsosa-filmaffinity`.`Actor` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
